### ISSUE TITLE
How to use existing modules (in HCL)?

### ISSUE THREAD

**Issue by ss-remygreinhofer** [NerdWalletOSS/terraformpy#55]
In the readme, it is mentioned:
> Modules have been explicitly excluded from this implementation because they aim to solve the same problem -- building reusable blocks in your Terraform configs.

Is there a trick to reuse existing TF modules we have? I would like to avoid having to convert them all to `ResourceCollection`.

**Comment by borgstrom** [comment]
It _should_ be trivial to add support for modules, but there is no built-in way to leverage them right now since we don't use them and no one has requested support thus far.

We would need to define a new object for `Module` that would be similar to the [`Provider`](https://github.com/NerdWalletOSS/terraformpy/blob/a81fbed/src/terraformpy/objects.py#L327) object.

Can you test this locally in your `main.tf.py` for me?  It would look something like:

```python
from terraformpy.objects import NamedObject


class Module(NamedObject):
    TF_TYPE = "module"


Module(
    "consul",
    source="hashicorp/consul/aws",
    version="0.0.5",

    servers=3
)
```

If everything works as expected we can add `Module` to the main distribution.

**Comment by ss-remygreinhofer** [comment]
Thanks a lot! It worked like a charm!
